- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - git
    state: present
    update_cache: yes

- name: добавить GPG ключ docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repository docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker and compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present

- name: add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes